"""Add manual_probe table

Revision ID: 1e21c03e2ae6
Revises: 0fd3bfb7f6de
Create Date: 2026-09-01 19:31:48.492491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e21c03e2ae6'
down_revision: Union[str, Sequence[str], None] = '0fd3bfb7f6de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_probes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farm_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('irrigation_value_mm', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], name=op.f('fk_manual_probes_farm_id_farm')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_probes'))
    )
    op.create_index(op.f('ix_manual_probes_id'), 'manual_probes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_probes_id'), table_name='manual_probes')
    op.drop_table('manual_probes')
    # ### end Alembic commands ###
