"""Add cultura, data_plantio, and potencia_cv to manual_probes

Revision ID: 2d42cdf172e0
Revises: f643477fd4ec
Create Date: 2026-09-08 20:45:12.396943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d42cdf172e0'
down_revision: Union[str, Sequence[str], None] = 'f643477fd4ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manual_probes', sa.Column('cultura', sa.String(length=64), nullable=True))
    op.add_column('manual_probes', sa.Column('data_plantio', sa.DateTime(), nullable=True))
    op.add_column('manual_probes', sa.Column('potencia_cv', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manual_probes', 'potencia_cv')
    op.drop_column('manual_probes', 'data_plantio')
    op.drop_column('manual_probes', 'cultura')
    # ### end Alembic commands ###
