"""add battery

Revision ID: 386d763a4417
Revises: 66289967e40b
Create Date: 2026-01-30 11:20:28.598374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '386d763a4417'
down_revision: Union[str, Sequence[str], None] = '66289967e40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('battery_status', sa.Integer(), nullable=True))
    op.add_column('reading', sa.Column('solar_status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading', 'solar_status')
    op.drop_column('reading', 'battery_status')
    # ### end Alembic commands ###
