"""add reading_type column

Revision ID: 5d24b5d299cc
Revises: 7596c0afa4dc
Create Date: 2026-01-13 17:36:23.017470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d24b5d299cc'
down_revision: Union[str, Sequence[str], None] = '7596c0afa4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('reading_type', sa.String(length=1), nullable=True))
    op.create_index(op.f('ix_reading_reading_type'), 'reading', ['reading_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reading_reading_type'), table_name='reading')
    op.drop_column('reading', 'reading_type')
    # ### end Alembic commands ###
