"""Add cultura_dap_potencia

Revision ID: 5d2d396f52ea
Revises: fac22c86f9d0
Create Date: 2026-04-10 12:51:23.943073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d2d396f52ea'
down_revision: Union[str, Sequence[str], None] = 'fac22c86f9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('cultura', sa.String(length=64), nullable=True))
    op.add_column('device', sa.Column('data_plantio', sa.Date(), nullable=True))
    op.add_column('device', sa.Column('potencia_cv', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'potencia_cv')
    op.drop_column('device', 'data_plantio')
    op.drop_column('device', 'cultura')
    # ### end Alembic commands ###
