"""Add moisture config columns to device

Revision ID: 66289967e40b
Revises: 5d24b5d299cc
Create Date: 2026-01-23 12:13:14.738232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66289967e40b'
down_revision: Union[str, Sequence[str], None] = '5d24b5d299cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('config_moisture_min', sa.Integer(), nullable=True))
    op.add_column('device', sa.Column('config_moisture_max', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'config_moisture_max')
    op.drop_column('device', 'config_moisture_min')
    # ### end Alembic commands ###
