"""add farm table and relationships

Revision ID: 72e63bd0b1e6
Revises: 00ec08ec6fb5
Create Date: 2025-12-12 18:02:08.275486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72e63bd0b1e6'
down_revision: Union[str, Sequence[str], None] = '00ec08ec6fb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_farm_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_farm'))
    )
    op.create_index(op.f('ix_farm_id'), 'farm', ['id'], unique=False)
    op.drop_index(op.f('ix_message_device_id'), table_name='message')
    op.drop_constraint(
        'fk_reading_message_id_message', 
        'reading', 
        type_='foreignkey'
    )
    op.drop_table('message')
    op.add_column('device', sa.Column('farm_id', sa.Integer(), nullable=True))
    op.alter_column('device', 'location',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('device', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('device', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_device_id'), 'device', ['id'], unique=False)
    op.create_foreign_key(op.f('fk_device_farm_id_farm'), 'device', 'farm', ['farm_id'], ['id'])
    op.alter_column('reading', 'depth_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_index(op.f('ix_reading_device_id'), table_name='reading')
    op.drop_index(op.f('ix_reading_timestamp'), table_name='reading')
    op.create_index(op.f('ix_reading_id'), 'reading', ['id'], unique=False)
    op.drop_column('reading', 'message_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_reading_message_id_message'), 'reading', 'message', ['message_id'], ['id'])
    op.drop_index(op.f('ix_reading_id'), table_name='reading')
    op.create_index(op.f('ix_reading_timestamp'), 'reading', ['timestamp'], unique=False)
    op.create_index(op.f('ix_reading_device_id'), 'reading', ['device_id'], unique=False)
    op.alter_column('reading', 'depth_cm',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('fk_device_farm_id_farm'), 'device', type_='foreignkey')
    op.drop_index(op.f('ix_device_id'), table_name='device')
    op.alter_column('device', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('device', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('device', 'location',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('device', 'farm_id')
    op.create_table('message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('raw_payload', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('received_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name=op.f('fk_message_device_id_device')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_message'))
    )
    op.create_index(op.f('ix_message_device_id'), 'message', ['device_id'], unique=False)
    op.drop_index(op.f('ix_farm_id'), table_name='farm')
    op.drop_table('farm')
    # ### end Alembic commands ###
