"""add lat long to device

Revision ID: 7596c0afa4dc
Revises: 72e63bd0b1e6
Create Date: 2026-01-09 11:48:09.154110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7596c0afa4dc'
down_revision: Union[str, Sequence[str], None] = '72e63bd0b1e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('device', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'longitude')
    op.drop_column('device', 'latitude')
    # ### end Alembic commands ###
