"""add rain_cm column

Revision ID: 9206e3ecb04c
Revises: 386d763a4417
Create Date: 2026-02-02 12:08:33.807589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9206e3ecb04c'
down_revision: Union[str, Sequence[str], None] = '386d763a4417'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reading', sa.Column('rain_cm', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reading', 'rain_cm')
    # ### end Alembic commands ###
