"""add moisture config columns to device

Revision ID: bab3ad9c90b7
Revises: 9206e3ecb04c
Create Date: 2026-03-16 19:18:35.733965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bab3ad9c90b7'
down_revision: Union[str, Sequence[str], None] = '9206e3ecb04c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('config_moisture_v1', sa.Float(), nullable=True))
    op.add_column('device', sa.Column('config_moisture_v2', sa.Float(), nullable=True))
    op.add_column('device', sa.Column('config_moisture_v3', sa.Float(), nullable=True))
    op.add_column('device', sa.Column('config_gradient_intensity', sa.Integer(), nullable=True))
    op.drop_column('device', 'config_moisture_max')
    op.drop_column('device', 'config_moisture_min')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('config_moisture_min', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('device', sa.Column('config_moisture_max', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('device', 'config_gradient_intensity')
    op.drop_column('device', 'config_moisture_v3')
    op.drop_column('device', 'config_moisture_v2')
    op.drop_column('device', 'config_moisture_v1')
    # ### end Alembic commands ###
