"""Add manual_irrigation_records table

Revision ID: f643477fd4ec
Revises: 1e21c03e2ae6
Create Date: 2026-09-01 20:29:54.343623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f643477fd4ec'
down_revision: Union[str, Sequence[str], None] = '1e21c03e2ae6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_irrigation_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manual_probe_id', sa.Integer(), nullable=False),
    sa.Column('irrigation_value_mm', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['manual_probe_id'], ['manual_probes.id'], name=op.f('fk_manual_irrigation_records_manual_probe_id_manual_probes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manual_irrigation_records'))
    )
    op.create_index(op.f('ix_manual_irrigation_records_id'), 'manual_irrigation_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_manual_irrigation_records_id'), table_name='manual_irrigation_records')
    op.drop_table('manual_irrigation_records')
    # ### end Alembic commands ###
