"""add_index_to_reading_device_time

Revision ID: fac22c86f9d0
Revises: bab3ad9c90b7
Create Date: 2026-03-17 10:30:08.920805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fac22c86f9d0'
down_revision: Union[str, Sequence[str], None] = 'bab3ad9c90b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_reading_device_time', 'reading', ['device_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reading_device_time', table_name='reading')
    # ### end Alembic commands ###
